"""
alerts.py — FaultAlert class for the Smart Campus Power Management System.

Provides severity-based alert objects that support priority ordering,
where CRITICAL sorts before WARNING before INFO.
"""

from dataclasses import dataclass, field
from datetime import datetime
from functools import total_ordering


# Severity priority map — lower number = higher priority
_SEVERITY_PRIORITY = {
    "CRITICAL": 0,
    "WARNING": 1,
    "INFO": 2,
}


@total_ordering
@dataclass
class FaultAlert:
    """
    Represents a fault alert generated by a meter or zone.

    Attributes:
        severity  (str): One of 'INFO', 'WARNING', or 'CRITICAL'.
        message   (str): Human-readable description of the fault.
        meter_id  (str): ID of the meter that triggered the alert.
        timestamp (datetime): When the alert was created.
    """

    severity: str
    message: str
    meter_id: str
    timestamp: datetime = field(default_factory=datetime.now)

    def __post_init__(self):
        self.severity = self.severity.upper()
        if self.severity not in _SEVERITY_PRIORITY:
            raise ValueError(
                f"Invalid severity '{self.severity}'. "
                f"Must be one of: {list(_SEVERITY_PRIORITY)}"
            )

    # ------------------------------------------------------------------ #
    # Ordering — CRITICAL (0) < WARNING (1) < INFO (2)                   #
    # So sorted() naturally puts CRITICAL first.                          #
    # ------------------------------------------------------------------ #

    def _priority(self) -> int:
        return _SEVERITY_PRIORITY[self.severity]

    def __lt__(self, other: "FaultAlert") -> bool:
        if not isinstance(other, FaultAlert):
            return NotImplemented
        return self._priority() < other._priority()

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, FaultAlert):
            return NotImplemented
        return (
            self.severity == other.severity
            and self.meter_id == other.meter_id
            and self.message == other.message
            and self.timestamp == other.timestamp
        )

    # ------------------------------------------------------------------ #
    # String representations                                              #
    # ------------------------------------------------------------------ #

    def __str__(self) -> str:
        return (
            f"[{self.severity}] {self.timestamp.strftime('%Y-%m-%d %H:%M:%S')} "
            f"| Meter {self.meter_id}: {self.message}"
        )

    def __repr__(self) -> str:
        return (
            f"FaultAlert(severity={self.severity!r}, meter_id={self.meter_id!r}, "
            f"message={self.message!r}, timestamp={self.timestamp!r})"
        )